apiVersion: skaffold/v4beta2
#apiVersion: skaffold/v3alpha1
kind: Config
#manifests:
#  rawYaml:
#  - service.yaml
manifests:
  kustomize:
    paths:
      - overlays/dev
  #hooks:
  #    before:
  #      - host:
  #          command: 
  #            ["sh", "-c", "gcloud run services delete quotes-front --region=us-central1 --quiet | cat"]
  #              ["sh", "-c", "gcloud run deploy service.yaml --region=us-central1 --quiet"]
  #              ["sh", "-c", "gcloud run services set-iam-policy quotes-front policy.yaml --region=us-central1 --quiet"]
  #          os: [darwin, linux]
  #    after:
  #      - host:
  #          command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front policy.yaml --region=us-central1 --quiet"]

metadata:
  name: quotes-front
build:
  artifacts:
  - image: quotes-front
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        REACT_APP_BACK_URL: app.dev.gabrielbechara.com

deploy:
  cloudrun:
    projectid: gab-devops-1
    region: us-central1
    hooks:
#      before:
#        - command: ["sh", "-c", "gcloud run services delete quotes-front --region=us-central1 --quiet | cat"]
      after:
       - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-dev policy.yaml --region=us-central1 --quiet | cat"]
       - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]

profiles:
- name: dev
  build:
    artifacts:
    - image: quotes-front
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          REACT_APP_BACK_URL: app.dev.gabrielbechara.com
  manifests:
    kustomize:
      paths:
        - overlays/dev
  deploy:
    cloudrun:
      projectid: gab-devops-1
      region: us-central1
      hooks:
        after:
        - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-dev policy.yaml --region=us-central1 --quiet | cat"]
# hooks are not used by cloud deploy, using verify instead
  verify:
  - name: apply-policy
    container:
      name: apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
#      command: ["/bin/sh"]
      entrypoint: 'bash'
      args: ["-c", "gcloud run services set-iam-policy quotes-front-dev policy.yaml --region=us-central1 --quiet | cat"]

- name: prod
  build:
    artifacts:
    - image: quotes-front
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          REACT_APP_BACK_URL: app.prod.gabrielbechara.com

  manifests:
    kustomize:
      paths:
        - overlays/prod
  deploy:
    cloudrun:
      projectid: gab-devops-1
      region: us-central1
      hooks:
        after:
        - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]
# hooks are not used by cloud deploy, using verify instead
  verify:
  - name: apply-policy
    container:
      name: apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
#      command: ["/bin/sh"]
      entrypoint: 'bash'
      args: ["-c", "gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]
