apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: quotes-front
 annotations:
  run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '2'
    spec:
      containers:
      - image: quotes-front
# for react env var are not read at runtime (kept this here for future usage)
#        env:
#          - name: APP_BACK_URL
#            value: app.dev.gabrielbechara.com